[general]
debug=false

[[mob]]
    name="minecraft:phantom"

    # - Spawns in The End
    [[mob.rule]]
        name="end"
        type="link"
        repeat=20
        cool-down=40
        spawn.count=3
        spawn.at-y=">80"
        dimension=["minecraft:the_end"]
        max-nearby=15
        max-nearby-range=100
        max-per-mob=100
        can-see-sky="yes"
        spawn.point="mobcontrol:air"

    # - Normal phantoms (end)
    [[mob.rule]]
        copy="end"
        type="control"
        set.damage=5
        set.health=10